---
title: "RAC Parking Report Automation---Queries for England, round 3"
author: mz
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
---
  
14. In *Surpluses* the third sentence is a repeat of one in the introduction section. I don't know, there is just so much data here, being so minimal and repeating yourself seems a bit daft...

15. In surpluses, we don't currenlty compare them with the total transport net expenditure (except nationally). In Scotland and Wales we did however. Do you want me to pull the council level data in for that as well and do the same for England?

16. In *Budget surplus comparison* : wouldn't it be cool to see the budgeted and realised surpluses for each council? And the proporiton difference?


17. The sentence 

> "The London boroughs, with their larger incomes, were more likely to have large excess surpluses compared with budget."

Is problematic, no? I mean  because they have larger incomes means they are bad at budgeting? I guess the variance is larger? Anyway, even if you think so, it's still a tricky sentence to leave in in case there comes a day when London boroughs get better at writing their budgets, and this isn't sth that can really be automated. Should I throw it out?

18. In *Comparison with budgets* I changed the text to read "compared with a budgeted deficit of XX" instead of "compared with a budget deficit", that makes more sense to me?


# finished draft following Leibling

OK, so now you have the draft England report that basically follows what Leibling had. So the following questions are to do with consolidating all three reports

19. The two  national comparison tables for the outturns and the average annual changes have now been repeated in all three reports. I've adjusted the text a bit to take into account that the data can be for different years. Which also means that e.g. GB data is calculated for the most recent year *all* countries have data avialable. I've added a bit more text in all three reports, because it's a shame to have so many numbers in tables and so little text. Check that this is OK in all 3 reports.



