---
title: "RAC Parking Report Automation---Queries for England, round 1"
author: mz
date: 12.9.2019
output:
  pdf_document: default
---

1. The england report introduction ends with the following paragraph:

> These headings do not always agree with accounts published by local authorities because of their different treatment of overheads and allocation of surpluses to other transport projects. Furthermore six local authorities include off-street parking in their internal trading accounts which leads to further inconsistencies. These trading figures have been added to the revenue accounts

Basically I do not really understand what this means. I mean I get the first part, if one were to compare this data with LA sources, there might be inconsistencies. But what does the last sentence mean? WHich trading figures? Which revenue accounts? Have been added by whom? Or is it by who? 

And back in april in an email from David he said :

> For your information, I also make an adjustment for trading activities for six councils in the English figures,  the largest of which is Plymouth. They are based on the RO table TSR which only shows the net income.  I assume, based on other similar activities, that the turnover is twice the surplus and the costs are equal to the surplus.  

So what do you want me to do with this?

2. Just a quick scan seems to indicate that the England reports do not contain any comparisons to Wales and Scotland like the others do. Do you want me to stick to the original England report as a template or should I try to include as much similar stuff as in the new Wales and Scotland reports as possible?

3. Should the introductory paragraph also include the source of the Nottingham WPL?

4. So removing the parks is easy, but how exactly do i remove the Nottingham WPL? e.g. for 2017 I have the following data for Nottingham city

* income from on street parking: 5,113 (pentalties = 1855, fees and permits = 3258)
* income from off street parking: 15,445
* -> total income = 20,558
* expenditure on street parking: 1,117
* expenditure off street parking: 4,907
-> total expenditure = 6,024
* and of course the surpluses: on street: 3,996 , off street: 10,538 and total surplus: 14,534.

WPL data is:

* wpl income: 9,178
* wpl expenditure: 219
* and of course there is a surplus: 8,959

So what do i do with this? Do I subtract the WPL income, expenditure and surplus from the off-street income, expenditure and surplus? e.g.  the new off street parking subtracting the levy would then be 15,445 - 9,178 = 6,267? and then i use this number in calculating the totals etc?







